org:
  ogier:
    modules: parent, async, api, persistence, service, resource, gateways, test, exe
    mandatorymodules : parent, exe
    nonbusinessmodules: exe, api, async, test
    excludesubmodules: api, async, parent
    intermoduledependency:
      resource: service, api
      gateways: service, async
      service: persistence
      exe: resource, service, persistence, gateways